---
- hosts: all
  remote_user: vagrant
  sudo: yes
  vars:
   - docroot: /var/www/html
  tasks:

    - name: Actualizando Repositorios
      apt: update_cache=yes

    - name: Instalando Apache2
      apt: name=apache2 update_cache=yes state=present

    - name: Instalando modulo PHP para Apache
      apt: name=libapache2-mod-php5 state=present 

    - name: Instalando PHP5
      apt: name=php5 state=installed

    - name: Instalando phpmyadmin
      apt: name=phpmyadmin state=installed

    - name: Instalando PHP5-gd
      apt: name=php5-gd state=installed

    - name: Instalando Mysql
      apt: name={{ item }} state=latest
      with_items:
        - php5-mysql
        - mysql-server
        - python-mysqldb

    - name: usuario
      mysql_user: name=drupal password=4321 priv=.*:ALL host=localhost

    - name: Iniciando Apache
      service: name=apache2 state=running enabled=yes

    - name: Creando base de datos
      mysql_db: name=drupal state=present

    - name: Instalando Git
      apt: name=git state=installed

    - name: Borrando Carpeta innecesarias
      command: rm -r /var/www/html

    - name: Creando carpeta para el repositorio
      command: mkdir -p /var/www/html/drupal

    - name: Borrando Carpeta innecesarias
      command: rm -r /var/www/html

    - name: Descargando y clonando el repositorio de drupal
      git: repo=https://github.com/hdpdrupal/drupal.git dest=/var/www/html

    - name: Agregando permisos
      command: chdir=/var/www/html/ chmod -R 0777 drupal

    - name: Intalando complemntos para drush
      command: wget http://ftp.drupal.org/files/projects/drush-7.x-5.1.tar.gz

    - name: Descomprimiendo
      command: tar -xzf drush-7.x-5.1.tar.gz

    - name: permisos drush
      command: chmod -R 0777 drush
   
    - name: enlace phpmyadmin
      command: ln -s /usr/share/phpmyadmin /var/www/html

    - name: enlace
      command: ln -s /home/vagrant/drush/drush /usr/local/bin/drush

    - name: permisos php.ini
      command: cp /var/www/html/drupal/php.ini /home/vagrant/drush

    - name: permisos php
      command: chdir=/home/vagrant/drush chmod 0777 php.ini
    
    - name: Instalando drupal
      command: chdir=/var/www/html/drupal drush site-install -y --db-url=mysql://root:@localhost/drupal --site-name="JCOMPUTADORAS" --account-name="cadenas" --account-pass="4321" --locale=es standard

    - name: Actualizando la base de datos
      action: mysql_db db=drupal state=absent

    - name: Creando base de datos
      mysql_db: name=drupal state=present

    - name: Importando base de datos
      mysql_db: name=drupal state=import target=/var/www/html/drupal/drupal.sql
